defaults: &defaults
  server: "https://ise.itech.pw:9292/faye"
  secret_token: "<%= ENV['PRIVATE_PUB_SECRET_TOKEN'] %>"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  signature_expiration: 3600 # one hour

sandbox:
  <<: *defaults
  signature_expiration: 3600 # one hour
