remnants_report:
  cron: '0 9 * * * Asia/Vladivostok'
  class: 'RemnantsReportMailingJob'
  queue: 'reports'
  active_job: true

sales_report:
  cron: '45 9 * * * Asia/Vladivostok'
  class: 'DailySalesReportMailingJob'
  queue: 'reports'
  active_job: true
